services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root-pass
      MYSQL_DATABASE: test-db
      MYSQL_USER: test-user
      MYSQL_PASSWORD: test-pass
    volumes:
      - db-data:/var/lib/mysql

  django:
    build: .
    container_name: django_container
    depends_on:
      - mysql
      - minio
    ports:
      - "8000:8000"
    volumes:
      - ./:/code

  minio:
    image: minio/minio
    container_name: minio_container
    command: server /data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001" # For MinIO Console (Optional)
    volumes:
      - minio-data:/data

volumes:
  db-data:
  minio-data:
