services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root-pass
      MYSQL_DATABASE: test-db
      MYSQL_USER: test-user
      MYSQL_PASSWORD: test-pass
    volumes:
      - db-data:/var/lib/mysql

  django:
    build: .
    container_name: django_container
    depends_on:
      - mysql
    ports:
      - "8000:8000"
    volumes:
      - ./:/code

volumes:
  db-data: